name: Web App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r web-app/requirements.txt

      # Start MongoDB container
      - name: Start MongoDB Container
        run: |
          docker run -d --name mongodb -e MONGO_INITDB_DATABASE=Outfits -p 27017:27017 mongo:latest

      # Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          for i in {1..9}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB failed to start."
          exit 1
      #env file
      - name: Create env file
        run: |
          cd ${{ matrix.subdir }}
          echo "MONGO_DBNAME=${{ secrets.MONGO_DB }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "FLASK_APP=app.py" >> .env
          echo "FLASK_ENV=development" >> .env
          echo "FLASK_PORT=5000" >> .env
          echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> .env


      # Run tests
      - name: Run Tests
        env:
          MONGO_DBNAME: Outfits
          MONGO_URI: mongodb://localhost:27017
        run: |
          pytest web-app/tests/
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jl8059
          password: qq883697776
      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t jl8059/web-app:latest ./web-app --push

      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: 159.203.137.174
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Navigate to the deployment directory
            cd /root/project

            # Pull the latest images from Docker Hub
            docker pull jl8059/web-app:latest

            docker stop web-app || true
            docker rm web-app || true
            docker-compose -f docker-compose.yml down || true
            docker-compose -f docker-compose.yml up --build -d